name: projGNN
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.08.22=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.10=h7f8727e_2
  - pip=23.2.1=py311h06a4308_0
  - python=3.11.5=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.0.0=py311h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.38.4=py311h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - certifi==2023.7.22
      - charset-normalizer==3.2.0
      - cmake==3.27.4.1
      - contourpy==1.1.0
      - cycler==0.11.0
      - cython==3.0.2
      - decorator==4.4.2
      - filelock==3.12.4
      - fonttools==4.42.1
      - idna==3.4
      - jinja2==3.1.2
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - lit==16.0.6
      - markupsafe==2.1.3
      - matplotlib==3.7.3
      - mpmath==1.3.0
      - networkx==3.1
      - numpy==1.25.2
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - packaging==23.1
      - pandas==1.3.5
      - pillow==10.0.0
      - psutil==5.9.5
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - requests==2.31.0
      - scikit-learn==1.3.0
      - scipy==1.11.2
      - six==1.16.0
      - sympy==1.12
      - threadpoolctl==3.2.0
      - torch==2.0.1
      - torch-geometric==2.3.1
      - torch-geometric-temporal==0.54.0
      - torch-scatter==2.1.1
      - torch-sparse==0.6.17
      - tqdm==4.66.1
      - triton==2.0.0
      - typing-extensions==4.7.1
      - tzdata==2023.3
      - urllib3==2.0.4
prefix: /home/gnn-variant/anaconda3/envs/projGNN
